url: http://jsonapi.org
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: redcarpet
port: 9876
