url: http://jsonapi.org
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
pygments: false
port: 9876

latest_version: 1.0

navigation:
- title: JSON API
  url: /
- title: Specification
  url: /format/
- title: Extensions
  url: /extensions/
- title: Recommendations
  url: /recommendations/
- title: Examples
  url: /examples/
- title: Implementations
  url: /implementations/
- title: FAQ
  url: /faq/
- title: About
  url: /about/

quicklinks:
- title: View the specification
  url: /format/
- title: Contribute on GitHub
  url: https://github.com/json-api/json-api
